linters:
  enable-all: false
  disable-all: true
  enable:
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  gocyclo:
    min-complexity: 16
  lll:
    line-length: 200